# Generated by Django 6.1 on 2026-09-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('operation_type', models.CharField(choices=[('FUND', 'Fund'), ('RELEASE', 'Release'), ('REFUND', 'Refund')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='payments.escrow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('escrow', 'operation_type'), name='unique_escrow_operation_type')],
            },
        ),
    ]
